[package]
name = "raytracing_101"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
winit = { version = "0.29.14", features = ["rwh_05"]}
num = "0.4.1"
